# Generated by CMake, DO NOT EDIT
/Users/Yang/Material/Research/dart/Xcode/CMakeFiles/cmake.check_cache: \
/Users/Yang/Material/Research/dart/apps/rigidBodies/CMakeLists.txt
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -H/Users/Yang/Material/Research/dart -B/Users/Yang/Material/Research/dart/Xcode
