/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class UnityOptimizationPlugin {

  private static void MarshalHelperWrite(ref IntPtr ptr, ref UnityEngine.Quaternion q)
  {
	Marshal.WriteInt32(ptr, Marshal.SizeOf(typeof(float)) * 0, BitConverter.ToInt32(BitConverter.GetBytes(q[3]), 0));
    Marshal.WriteInt32(ptr, Marshal.SizeOf(typeof(float)) * 1, BitConverter.ToInt32(BitConverter.GetBytes(q[0]), 0)); 
	Marshal.WriteInt32(ptr, Marshal.SizeOf(typeof(float)) * 2, BitConverter.ToInt32(BitConverter.GetBytes(q[1]), 0));
    Marshal.WriteInt32(ptr, Marshal.SizeOf(typeof(float)) * 3, BitConverter.ToInt32(BitConverter.GetBytes(q[2]), 0));
  }

  private static void MarshalHelperRead(ref IntPtr ptr, out UnityEngine.Quaternion q)
  {
    q = new UnityEngine.Quaternion(BitConverter.ToSingle(BitConverter.GetBytes(Marshal.ReadInt32(ptr, Marshal.SizeOf(typeof(float)) * 1)), 0),
	                               BitConverter.ToSingle(BitConverter.GetBytes(Marshal.ReadInt32(ptr, Marshal.SizeOf(typeof(float)) * 2)), 0),
								   BitConverter.ToSingle(BitConverter.GetBytes(Marshal.ReadInt32(ptr, Marshal.SizeOf(typeof(float)) * 3)), 0),
								   BitConverter.ToSingle(BitConverter.GetBytes(Marshal.ReadInt32(ptr, Marshal.SizeOf(typeof(float)) * 0)), 0));
  }

}
