/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class UnityOptimizationPluginPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("UnityOptimizationPlugin", EntryPoint="SWIGRegisterExceptionCallbacks_UnityOptimizationPlugin")]
    public static extern void SWIGRegisterExceptionCallbacks_UnityOptimizationPlugin(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("UnityOptimizationPlugin", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_UnityOptimizationPlugin")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_UnityOptimizationPlugin(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_UnityOptimizationPlugin(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_UnityOptimizationPlugin(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(UnityOptimizationPluginPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(UnityOptimizationPluginPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("UnityOptimizationPlugin", EntryPoint="SWIGRegisterStringCallback_UnityOptimizationPlugin")]
    public static extern void SWIGRegisterStringCallback_UnityOptimizationPlugin(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_UnityOptimizationPlugin(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static UnityOptimizationPluginPINVOKE() {
  }


  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_new_ControlPBP")]
  public static extern IntPtr new_ControlPBP();

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_delete_ControlPBP")]
  public static extern void delete_ControlPBP(HandleRef jarg1);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_init")]
  public static extern void ControlPBP_init(HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, HandleRef jarg6, HandleRef jarg7, HandleRef jarg8, HandleRef jarg9, HandleRef jarg10, HandleRef jarg11, float jarg12, HandleRef jarg13);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_update__SWIG_0")]
  public static extern void ControlPBP_update__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4, HandleRef jarg5);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_update__SWIG_1")]
  public static extern void ControlPBP_update__SWIG_1(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getSquaredCost")]
  public static extern double ControlPBP_getSquaredCost(HandleRef jarg1);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getBestControl")]
  public static extern void ControlPBP_getBestControl(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getBestControlState")]
  public static extern void ControlPBP_getBestControlState(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getBestTrajectoryOriginalStateCost")]
  public static extern double ControlPBP_getBestTrajectoryOriginalStateCost(HandleRef jarg1, int jarg2);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_setSamplingParams")]
  public static extern void ControlPBP_setSamplingParams(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4, float jarg5, HandleRef jarg6);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_startIteration")]
  public static extern void ControlPBP_startIteration(HandleRef jarg1, bool jarg2, HandleRef jarg3);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_startPlanningStep")]
  public static extern void ControlPBP_startPlanningStep(HandleRef jarg1, int jarg2);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getPreviousSampleIdx")]
  public static extern int ControlPBP_getPreviousSampleIdx(HandleRef jarg1, int jarg2);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getControl__SWIG_0")]
  public static extern void ControlPBP_getControl__SWIG_0(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4, HandleRef jarg5);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getControl__SWIG_1")]
  public static extern void ControlPBP_getControl__SWIG_1(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getControl__SWIG_2")]
  public static extern void ControlPBP_getControl__SWIG_2(HandleRef jarg1, int jarg2, HandleRef jarg3);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_updateResults__SWIG_0")]
  public static extern void ControlPBP_updateResults__SWIG_0(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4, double jarg5, HandleRef jarg6, HandleRef jarg7);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_updateResults__SWIG_1")]
  public static extern void ControlPBP_updateResults__SWIG_1(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4, double jarg5, HandleRef jarg6);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_updateResults__SWIG_2")]
  public static extern void ControlPBP_updateResults__SWIG_2(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4, double jarg5);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_endPlanningStep")]
  public static extern void ControlPBP_endPlanningStep(HandleRef jarg1, int jarg2);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_endIteration")]
  public static extern void ControlPBP_endIteration(HandleRef jarg1);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_setParams")]
  public static extern void ControlPBP_setParams(HandleRef jarg1, double jarg2, double jarg3, bool jarg4, float jarg5);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_gaussianBackPropagation__SWIG_0")]
  public static extern void ControlPBP_gaussianBackPropagation__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_gaussianBackPropagation__SWIG_1")]
  public static extern void ControlPBP_gaussianBackPropagation__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_gaussianBackPropagation__SWIG_2")]
  public static extern void ControlPBP_gaussianBackPropagation__SWIG_2(HandleRef jarg1);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getBestSampleLastIdx")]
  public static extern int ControlPBP_getBestSampleLastIdx(HandleRef jarg1);

  [DllImport("UnityOptimizationPlugin", EntryPoint="CSharp_ControlPBP_getGBPRegularization")]
  public static extern float ControlPBP_getGBPRegularization(HandleRef jarg1);
}
